### PR TITLE
Fix/responsive navbar

### PR DESCRIPTION
**Pull request by freefony**

### CODE REVIEW

**Comment by tlvince** [comment]
This can be implemented without having to pull in jQuery and Bootstrap's JS via UI Bootstrap's [collapse](https://angular-ui.github.io/bootstrap/#/collapse) directive. See the source of those docs for an example.

**Comment by jofomah** [comment]
@tlvince a quick look at the link means, by default, the navbar will be a hamburger menu, is there a way we can make it responsive hamburger menu i.e only on small devices?

**Comment by tlvince** [comment]
Yes, sure, just add the `visible-xs` class?

**Comment by freefony** [comment]
updated in #125

**Comment by tlvince** [comment]
Super dooper!

**Pull request closed without merging**
