### PR TITLE
WIP: feature/cordova

### PR DESCRIPTION
**Pull request by hbj**
To test:
* install Android SDK and set ANDROID_HOME env var or add the SDK to the PATH
* run `gulp build cordova` (add `--release` parameter for realease build)

Currently the APK is not signed, need to find out how to implement it.

### CODE REVIEW

**Comment by tlvince** [comment]
@hbj, Crosswalk, platform-specific builds and uploading the resulting APKs to S3 would be nice to have. @rmehner may be of assistance here (via the [followup app buildchain](https://github.com/eHealthAfrica/lr-sense-ebola-followup/tree/develop/scripts)).

**Comment by hbj** [comment]
@tlvince what do you mean with 'platform-specific builds'?

**Comment by tlvince** [comment]
Sorry, I meant architecture, i86 vs amd7. Or we should find out the architecture of our target tablets and build for that

**Comment by tlvince** [comment]
Lets shelve the enhancements for now. Is this otherwise good to go?

**Comment by tlvince** [comment]
We can add signing later (a debug build is fine for now).

**Comment by hbj** [comment]
Yes this should be ready

**Comment by tlvince** [comment]
Enhancements ticketed. Just a slight tweak to the package ID for consistency with our other apps (#98). Thanks!

**Pull request closed without merging**
