### PR TITLE
Refactor/split delivery document to be per facility delivery

### LINKED ISSUE #252: split the delivery document to be per facility delivery

### PR DESCRIPTION
**Pull request by musamusa**
Closes #252

### CODE REVIEW

**Comment by jofomah** [comment]
@musamusa please fix this, i want to test the mobile app and how it works with both old delivery document structure and the new per delivery per doc structure. thanks

**Comment by tlvince** [comment]
@musamusa @jofomah Travis/karma fixed.

**Comment by jofomah** [comment]
This should only be merged  cx VDD dashboard complimentary mobile app release.

**Comment by jofomah** [comment]
@musamusa LGTM except that i couldn't access Packing List tab and i can't see where in the code packingList is extracted from existing document that has the old format. am thinking we should do the following if it makes sense to you:

1. fetch dailyDelivery document for the given driver and date.
2. use each daily delivery packedProduct to form a packing list doc if one does not exist already

**Comment by tlvince** [comment]
Closing in favour of #262.

**Pull request closed without merging**
