### PR TITLE
Fix/hide sync msg offline

### PR DESCRIPTION
**Pull request by freefony**

### CODE REVIEW

**Comment by tlvince** [comment]
@jofomah this includes an outdated `gulp/cordova.js`. Looks like a bad merge.

**Comment by tlvince** [comment]
(The cordova scripts were split in `gulp/cordova/{build,move}` before this)

**Comment by jofomah** [comment]
@tlvince, will try and fix that with a branch before the merge and send in
the PR.

**Comment by tlvince** [comment]
@jofomah see #136.

**Pull request merged**
