### PR TITLE
feat(analytics): add Google Analytics

### LINKED ISSUE #238: Add analytics service
Ref https://github.com/eHealthAfrica/move/issues/77

### PR DESCRIPTION
**Pull request by tlvince**
Adds Google Analytics module, see:
https://github.com/eHealthAfrica/angular-eha.cordova.google-analytics

Closes #238.

### CODE REVIEW

**Comment by tlvince** [comment]
Note, this is just a basic integration. You might want to track clicks with the [eha-ga-click](https://github.com/eHealthAfrica/angular-eha.cordova.google-analytics#ehagaclick) directive (where it makes sense), or add user tracking.

**Comment by janetbutts** [comment]
hey @jofomah , please review for tom.

**Comment by janetbutts** [comment]
@jofomah , please review for @tlvince .

**Comment by tlvince** [comment]
@jofomah how about this? Rebased.

**Comment by janetbutts** [comment]
@musamusa , please review

**Comment by musamusa** [comment]
@tlvince can you resolve conflict so I an merge this

**Comment by tlvince** [comment]
Will do.

**Comment by tlvince** [comment]
@musamusa fixed.

**Pull request merged**
