### PR TITLE
Adds packing list

### PR DESCRIPTION
**Pull request by tlvince**
Sorry this got so large. In summary:

* Adds packing list read and update views
* Packing aggregate is implemented as a Couch "join" (using complex keys and view collation tricks, see "[Joins with views](http://docs.couchdb.org/en/1.6.1/couchapp/views/joins.html))
* Manages Couch views in the repo
* Adds local fixtures (hoped to generate these via [data_model](https://github.com/eHealthAfrica/data_model), but time didn't permit)
* However, pushed schemas back up to data_model
* Adds specs
* Adds lightweight Couch service (penned to be replaced with Pouch)

Usage:

```
curl -X PUT http://localhost:5984/deliveries/ && gulp views fixtures-local serve
```

### CODE REVIEW

**Comment by hbj** [comment]
Why do we have the documents of type `packingList`? Couldn't we have them directly included in their `dailyDelivery` documents summed up? e.g. instead of having this:

```json
[
  {
    "doc_type": "packingList",
    "version": "1.0.0",
    "productID": "BCG",
    "expectedQty": 10,
    "dailyDeliveryID": "d8006b0524473a0a4a60b7749766a11d"
  },
  {
    "doc_type": "packingList",
    "version": "1.0.0",
    "productID": "BCG",
    "expectedQty": 200,
    "dailyDeliveryID": "d8006b0524473a0a4a60b7749766a11d"
  },
  {
    "doc_type": "packingList",
    "version": "1.0.0",
    "productID": "Men-A",
    "expectedQty": 150,
    "dailyDeliveryID": "d8006b0524473a0a4a60b7749766a11d"
  },
  {
    "_id": "d8006b0524473a0a4a60b7749766a11d",
    "doc_type": "dailyDelivery",
    "version": "1.0.0",
    "deliveryRoundID": "d8006b0524473a0a4a60b7749766a11e",
    "driverID": "abdullahi.ahmed@example.com",
    "facilityRounds": []
  }
]
```

we would have:

```json
{
  "_id": "d8006b0524473a0a4a60b7749766a11d",
  "doc_type": "dailyDelivery",
  "version": "1.0.0",
  "deliveryRoundID": "d8006b0524473a0a4a60b7749766a11e",
  "driverID": "abdullahi.ahmed@example.com",
  "facilityRounds": [],
  "packingList": [
    {
      "productID": "BCG",
      "expectedQty": 210
    },
    {
      "productID": "Men-A",
      "expectedQty": 150
    }
  ]
}
```

and after packing:

```json
{
  "_id": "d8006b0524473a0a4a60b7749766a11d",
  "doc_type": "dailyDelivery",
  "version": "1.0.0",
  "deliveryRoundID": "d8006b0524473a0a4a60b7749766a11e",
  "driverID": "abdullahi.ahmed@example.com",
  "facilityRounds": [],
  "packingList": [
    {
      "productID": "BCG",
      "expectedQty": 210,
      "packedQty": 210
    },
    {
      "productID": "Men-A",
      "expectedQty": 150,
      "packedQty": 141
    }
  ],
  "packedDate": "2015-01-07T15:05:29.285Z"
}
```

**Comment by tlvince** [comment]
Seems reasonable to me. The current implementation is based off @jofomah's data model. Maybe he'll have some input here?

If we don't need such fine grained normalisation (will these records be used elsewhere or solely the dailyDelivery object?), I'm fine with embedding them.

**Comment by hbj** [comment]
If a user sets the packed quantities for a packing list and reopen it, the packed quantities are not retrieved and displayed. Is that intentional?

**Comment by tlvince** [comment]
Nope. I'll fix that.

NB, probably in the main list screen there should be some indicator of lists that have been edited.

**Comment by jofomah** [comment]
@tlvince and @hbj please, this is the latest data model diagram, https://drive.draw.io/#G0B3JqadXCUEcVUkREYkk5cjBHeDQ  it says DailyDelivery contains PackingList. which means i assumed PackingList will be an array inside Daily Delivery.

@tlvince, maybe you didnt get this latest diagram which was modified after discussions with Haykel before my leave.

for now, am not sure we need the normalized form. sorry for the confusion.

**Comment by hbj** [comment]
In the diagram, how are the `packedProduct` items created? Are they somehow related to `packingList` items in the current implementation?

**Comment by jofomah** [comment]
@hbj, from my understanding, packingList is the complete list of products, drivers are supposed to pack for the day independent of each facility needs, their the packedProduct is "packingList" for each facility, am not sure if packing list for daily delivery should be auto produced from each facility packedProucts (each facility packing list) that is another way to look at it. maybe we need to reconfirm from Michael.

**Comment by tlvince** [comment]
No probs. I'll get on it.

**Comment by hbj** [comment]
From my understanding of the round google sheet, the packing lists of every facility are defined individually ('Planning' sheet) and the total packing list content ('Packing List' sheet) is calculated automatically from the facility packing lists.

**Comment by jofomah** [comment]
Yes! if you mean the counter.

check this one:

https://docs.google.com/a/ehealthnigeria.org/spreadsheets/d/1zAPUkZLYAhofRuv2SDVzweajUE7SkZxmG_7KQSF4ahY/edit#gid=1793307880

the packing list tab is a sum of quantities of each item to be packed by a driver independent of each facility needs.
but after daily delivery, they need to record quantity of each product returned to the store, doing that individually for each facility visited won't be feasible or comfortable in my humble opinion.

i looked at it this way,

1. they have quantity to supply at each facility.
2. Available quantity available of each product at the store might be less than what is specified to pack.
3. After delivery, they record what was returned to the store this from my understanding is not done per facility.

i think having the following will be better
1. a daily packing list of what to pack independent of each needs, which is the packing list, this will be used to record what was packed, what was returned, expected packing quantity.

hence, i think separating the Packing List(https://docs.google.com/a/ehealthnigeria.org/spreadsheets/d/1zAPUkZLYAhofRuv2SDVzweajUE7SkZxmG_7KQSF4ahY/edit#gid=1793307880) and Counter (https://docs.google.com/a/ehealthnigeria.org/spreadsheets/d/1X2rRZeAbuQ6XJdctR6OIBkyNeIMYCZpiAV5xgpfBsJA/edit#gid=0) is better.

but we can re-confirm from Michael. he has more information about this than i do.

**Comment by jofomah** [comment]
@hbj is this ready to be merged??

**Comment by tlvince** [comment]
Not yet…

**Comment by tlvince** [comment]
@hbj, rebased and embedded packing list. Note, you'll probably have to reset your local CouchDB:

```
for i in DELETE PUT; do curl -X $i http://localhost:5984/deliveries/; done && gulp views fixtures-local
```

**Comment by tlvince** [comment]
See [build-32](https://travis-ci.org/tlvince/direct-delivery/builds/46318630) for Travis results.

**Comment by hbj** [comment]
Last thing for now: when you save a packing list, it is still displayed in the 'Current' section while it should go to 'History'.

**Comment by tlvince** [comment]
Whoops. Done.

**Comment by hbj** [comment]
Is it OK to save a packing list without setting the packed quantity for some or all products?

**Pull request merged**
