### PR TITLE
Schedule service to use auth user

### PR DESCRIPTION
**Pull request by freefony**

### CODE REVIEW

**Comment by tlvince** [comment]
Has this got mixed up with the PouchDB schedule service pull request?

**Comment by freefony** [comment]
yeah i kinda think so. Jide's comment was from yesterday

**Comment by freefony** [comment]
How can that be?

**Comment by tlvince** [comment]
Maybe you're working in the same branch as the previous pull request?

**Comment by freefony** [comment]
nope!!!!!!

**Pull request closed without merging**
