### PR TITLE
Add eHealth bootstrap theme

### PR DESCRIPTION
**Pull request by tlvince**

### CODE REVIEW

**Comment by jofomah** [comment]
@tlvince Michael talked about making the text and buttons bigger when he saw the built apk. is there a way we can increase base font size from this theme??

**Comment by tlvince** [comment]
We still have access to the underlying Bootstrap variables, so yes.

**Comment by tlvince** [comment]
Increased font size slightly.

**Comment by jofomah** [comment]
@tlvince will merge this in, even though there is no noticeable difference in size of font and UI element. will apply input-lg and btn-lg to all input fields and buttons, then see how it looks.

**Comment by tlvince** [comment]
You can bump it some more in `vendor.scss` if you like.

**Pull request merged**
