### PR TITLE
Refactor/split delivery document to be per facility delivery

### LINKED ISSUE #252: split the delivery document to be per facility delivery

### PR DESCRIPTION
**Pull request by tlvince**
Continuation of #253.

Closes #252.

### CODE REVIEW

**Comment by tlvince** [comment]
@jofomah does this work for you? I'm using driver `a@a.com`.

**Comment by tlvince** [comment]
@jofomah rebased.

**Comment by jofomah** [comment]
@tlvince still failing

**Comment by tlvince** [comment]
Whyowhy

**Comment by tlvince** [comment]
Should work now :pray:

**Comment by jofomah** [comment]
@musamusa @tlvince 
i got this to work but there are issues:
1. Packing list tab is empty even when i have deliveries for that day that has packed product. my guess if a document is not split already, it does not fetch the packing list, because `packing-list` doc does not exist.

- Do we need a migrator that will split existing documents, though Dashboard does not create packing list and it seems logical to generate packing doc by collating each delivery doc packed product.

- Should we generate Packing List doc if it does not exist dynamically off Split or compound daily delivery doc packed products?

your thoughts?

**Comment by musamusa** [comment]
@jofomah, 
1, **"*my guess if a document is not split already it does not fetch the packing list*"!**  exactly
2, **"*Do we need a migrator that will split existing documents*"**, That was what I had in mind
3, **"*Should we generate Packing List doc if it does not exist dynamically off Split*"**, that's was I was going for originally but had some issues, so I thought of solution above (sorry I didn't discuss it with you)

**Comment by janetbutts** [comment]
@tlvince ,  please pick up this issue as Musa is working on another project. it will be the main priority upon your return. thx

**Pull request closed without merging**
