### PR TITLE
Build with Crosswalk webview

### PR DESCRIPTION
**Pull request by tlvince**

### CODE REVIEW

**Comment by jofomah** [comment]
@tlvince is there any special reason why we changed out build target to Android 21???

**Comment by tlvince** [comment]
Yeah, that's what Crosswalk 11 specifies. AFAIK, it's back compatible

**Comment by jofomah** [comment]
@tlvince, ok just want to be sure we don't have to worry about backward
compatibility cause most devices here run on Android API < 21. cool.

**Comment by tlvince** [comment]
We should test it on a tablet first to be sure. I'll send you a build.

NB, this is what gets added to AndroidManifest.xml:

```xml
    <uses-sdk android:minSdkVersion="10" android:targetSdkVersion="21" />
```

**Comment by jofomah** [comment]
yeah, trying to install Android API 21 using SDK manager but it is taking time to get the complete package. once am done i will do that or i will use the one you send. if everything works fine, then i will merge this in.

**Pull request merged**
