### PR TITLE
Feature/auth

### PR DESCRIPTION
**Pull request by hbj**
Authentication service and login page. Currently all pages are considered private and can only be accessed by authenticated users.

The first authentication in a day must be done against the CouchDB server. When that succeeds, the username and a hashed version of the password are saved in local storage and are by default used in all next authentication attempts of the same day, so the user can login without the need for an internet connection.

### CODE REVIEW

**Comment by tlvince** [comment]
I think we should confirm with the stakeholders on the security requirements, but an approach we could use is while offline, to namespace users' data under their login and assume good faith with regards to local security.

All said and done, I can't think of a way to do true offline authentication. A couple of strategies:

* One user per device: does not fit our requirements

* Offload authentication to Android system accounts: no-to-flakey support in Kitkat (though it [seems like it's coming in Lollipop](http://www.androidcentral.com/lollipop-brings-proper-multi-user-accounts-your-phone)

* While offline and logged out, write to a "guest" account: AFAICT, how [Hood.ie](http://hood.ie) does it. Doesn't fit for us because we need multi-user support

* Pseudo offline accounts (i.e. namespaced storage as mentioned above): simplest method that could work? If security is a concern, maybe when online and logged in, show a "you have unsynched records" message and add an approve/reject flow before synching so the user can dispose of rogue entries if someone has logged in under their name?

* Local copy of password hashes (the method proposed here): how do we handle password invalidation? What happens if a user changes their password and tries to log in to another device that hasn't synched? Reverse engineering concerns? How about new signups while offline? Will every device have to carry a copy of everyone's hashed password?

* Asymmetric cryptography, i.e. public-private keys: this is the real solution, but browser crypto is too immature. See [keyboot](http://substack.net/offline_decentralized_single_sign_on_in_the_browser) of how it might look one day.

**Comment by hbj** [comment]
Regarding current implementation:

* The user must authenticate against the couch server at least once a day
* The user credentials are saved locally only after a successful server authentication
* The user credentials are only valid for one calendar day
* On every application start, old user credentials are deleted

Regarding namespacing user data, I think we should anyway use one db per user for user-specific data.

**Comment by tlvince** [comment]
Yeah, sorry, I'm conflating the issue somewhat. Tested all as you describe and its working fine.

I think the remaining issue we need to iron out is how we deal with multi-user offline sessions. With the current implementation, each user needs to have signed up and logged into the device they intend to use offline at least once. That might be something we just have to enforce, or otherwise, we need to support something akin to guest accounts.

**Comment by tlvince** [comment]
As per the Sprint.ly discussion, I think this is good to go. One day I'd like to explore not storing hashes, but for timeliness' sake, we need to move forward.

A few nitpicks:

* [ ] I'm getting `asmCrypto PRNG not seeded; your security relies on your system PRNG. If this is not acceptable, use asmCrypto.random.seed().` in the console
* [ ] Could you use `$window.moment` and `$window.asmCrypto` (or better, create wrapper services for them so they can be mocked)
* [ ] Could you fix the lint warnings? (`./node_modules/.bin/eslint src`, ignore `config.js`)
* [ ] Could you add some specs?

**Comment by hbj** [comment]
* asmCrypto message: generated when creating a random value to seed the asmCrypto PRNG, because obviously the PRNG has not yet been seeded at that time :)
* moment/asmCrypto services: do we really need them, we could just replace them for mocking?
* what do you mean with 'add some specs'?

**Comment by tlvince** [comment]
* "moment/asmCrypto services", I just mean something like:

```js
angular.factory('moment', function($window) {
  return $window.moment;
});
```

… or just do `$window.moment` if you don't think we need to mock them.

* Add some specs: some unit tests :)

**Comment by tlvince** [comment]
Merging this to prevent it from going stale and the fact that we need it going forward. Will ticket enhancements and specs.

**Comment by hbj** [comment]
We will have issues with some of the services, especially the packing pages as they don't use credentials in their http calls. I wanted to include fixes for it in this PR.

**Comment by tlvince** [comment]
Ah okay. We needed to merge it for the demo. Could you file some issues?

**Pull request merged**
