### PR TITLE
chore: update Cordova and Crosswalk

### LINKED ISSUE #190: Update Crosswalk
Per https://github.com/eHealthAfrica/lr-sense-ebola-followup/pull/298

### PR DESCRIPTION
**Pull request by tlvince**
Depends on #260.

Closes #190.

### CODE REVIEW

**Comment by janetbutts** [comment]
@freefony , please review

**Comment by tlvince** [comment]
Lets wait until #260 has been reviewed before looking at this one.

**Comment by tlvince** [comment]
@freefony rebased.

**Comment by janetbutts** [comment]
@freefony , please review.

**Comment by freefony** [comment]
@tlvince , please resolve conflicts

**Comment by tlvince** [comment]
@freefony done.

**Pull request merged**
