### PR TITLE
Packing list table legend

### PR DESCRIPTION
**Pull request by tlvince**
Adds a legend for the table's colour coding.

Closes item:1091.

### CODE REVIEW

**Comment by hbj** [comment]
Are popovers usable on touch devices?

**Comment by tlvince** [comment]
Yeah, good point. I'll check that.

**Comment by tlvince** [comment]
@hbj, tested on my phone (and in the Chrome emulator; enable "emulate touch screen", see screenshot) and the popovers are working fine.

screen shot 2015-01-17 at 20 32 50

**Comment by hbj** [comment]
@tlvince Rebase please.

**Comment by tlvince** [comment]
@hbj, rebased.

**Comment by hbj** [comment]
@tlvince I would merge but you need to rebase again :)

**Comment by tlvince** [comment]
@hbj, rebased.

**Pull request merged**
